
project:
  type: website

website:
  title: "AlennaNew"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: travel.qmd
        text: Travel
      - href: reflections.qmd
        text: Reflections

format:
  html:
    theme: cosmo
    css: style.css
    toc: true


