

project:
  type: website

website:
  title: "AlennaNew"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - travel.qmd
      - reflections.qmd
      

format:
  html:
    theme: cosmo
    css: style.css
    toc: true

editor: visual
